// Generated by gencpp from file beginner_hiwonder/Person.msg
// DO NOT EDIT!


#ifndef BEGINNER_HIWONDER_MESSAGE_PERSON_H
#define BEGINNER_HIWONDER_MESSAGE_PERSON_H

#include <ros/service_traits.h>


#include <beginner_hiwonder/PersonRequest.h>
#include <beginner_hiwonder/PersonResponse.h>


namespace beginner_hiwonder
{

struct Person
{

typedef PersonRequest Request;
typedef PersonResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Person
} // namespace beginner_hiwonder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_hiwonder::Person > {
  static const char* value()
  {
    return "8252a159fd1a6ef4321e6f234278121d";
  }

  static const char* value(const ::beginner_hiwonder::Person&) { return value(); }
};

template<>
struct DataType< ::beginner_hiwonder::Person > {
  static const char* value()
  {
    return "beginner_hiwonder/Person";
  }

  static const char* value(const ::beginner_hiwonder::Person&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_hiwonder::PersonRequest> should match
// service_traits::MD5Sum< ::beginner_hiwonder::Person >
template<>
struct MD5Sum< ::beginner_hiwonder::PersonRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_hiwonder::Person >::value();
  }
  static const char* value(const ::beginner_hiwonder::PersonRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_hiwonder::PersonRequest> should match
// service_traits::DataType< ::beginner_hiwonder::Person >
template<>
struct DataType< ::beginner_hiwonder::PersonRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_hiwonder::Person >::value();
  }
  static const char* value(const ::beginner_hiwonder::PersonRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_hiwonder::PersonResponse> should match
// service_traits::MD5Sum< ::beginner_hiwonder::Person >
template<>
struct MD5Sum< ::beginner_hiwonder::PersonResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_hiwonder::Person >::value();
  }
  static const char* value(const ::beginner_hiwonder::PersonResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_hiwonder::PersonResponse> should match
// service_traits::DataType< ::beginner_hiwonder::Person >
template<>
struct DataType< ::beginner_hiwonder::PersonResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_hiwonder::Person >::value();
  }
  static const char* value(const ::beginner_hiwonder::PersonResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_HIWONDER_MESSAGE_PERSON_H
